# Site settings
title: ä¸€ä¹‹ç¬”
SEOTitle: ä¸€ä¹‹ç¬”çš„åšå®¢ | Yizibi Blog
header-img: img/home-bg.jpg
email: liluxinios@gmail.com
description: "iOS å¼€å‘ å…¬å¸åˆä¼™äºº | æéœ²é‘«ï¼ŒiOS & Photography Loverï¼ŒSoftware Engineerï¼ŒEntrepreneur | è¿™é‡Œæ˜¯ @Yizibbi æéœ²é‘« çš„ä¸ªäººåšå®¢ï¼Œ ç”Ÿæ´»éœ€è¦ä»ªå¼æ„Ÿï¼ŒğŸ’ªã€‚"
keyword: "æéœ²é‘«, Yizibi,yizibi,ä¸€ä¹‹ç¬”çš„åšå®¢,ä¸€ä¹‹ç¬”,ä¸€æ”¯ç¬”, iOS, å…¬å¸åˆä¼™äºº, @yizibi, @yizibiçš„åšå®¢, åšå®¢, ä¸ªäººç½‘ç«™, äº’è”ç½‘"
url: "https://yizibi.github.io/"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username:     2524618644
zhihu_username:     li-lin-fei
github_username:    yizibi
twitter_username:   yizibi
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
textColor: #FF0000
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings

# disqus_username: Lucy

# Netease settings
netease_comment: false

gitalk:
    enable: true
    owner: yizibi
    repo: yizibi.github.io
    clientID: 3e12c08c2ec52afbcb30
    clientSecret: c2a74d279e7b42cf782a1d2d1b5a410d27c5ab57
    admin: yizibi


# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-124793396-1'            # Format: UA-xxxxxx-xx
ga_domain: auto



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "For the next quantum leap<br>ç”Ÿæ´»éœ€è¦ä»ªå¼æ„ŸğŸ’ª"
sidebar-avatar: /img/avatar-hux-ny.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: false



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
    {
        title: "ibiremeçš„åšå®¢ ",
        href: "https://blog.ibireme.com/"
     },{
        title: "å†°éœœä¹‹åœ°",
        href: "https://halfrost.com/"
    },{
	title: "Casa Taloyum",
	href: "https://casatwy.com/"
    },{
	title: "Junhua's Blog",
	href: "https://blog.searchinfogo.com"
    },{
	title: "å–µç¥ (@onevcat)",
	href: "https://onevcat.com/"
    },{
	title: "ç‰ä»¤å¤©ä¸‹",
	href: "http://yulingtianxia.com/"
    },{
	title: "åŸè´¥ç¬ç­±é¾™",
	href: "http://ilongge.cn/"
    },{
	title: "Lara Croft",
	href: "http://tombraiderjf.com/"
    }
]
